apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-crawler-service
  labels: 
    app: website-crawler-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
        name: website-crawler-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: website-crawler-service
        app: website-crawler-service
        tier: backend
    spec:
      containers:
      - name: website-crawler-service
        image: index.docker.io/catallicpankaj/website-crawler:latest
        args: ["--spring.profiles.active=${SPRING_PROFILE}",
               "--spring.config.location=classpath:/,classpath:/config/,file:./ymls/,file:./ymls/config/"]
        volumeMounts:
        - name: website-crawler-service-ymls-volume
          mountPath: /usr/src/app/ymls/config/
        ports:
        - name: http-ra-srv
          containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: ${ENVIRONMENT}
        resources:
          requests:
            memory: "768Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 3
      volumes:
      - name:  website-crawler-service-ymls-volume
        configMap:
          name:  website-crawler-service-ymls
#      imagePullSecrets:
#      - name: dockerconnection  - need to enable if want to use imagePullSecrets.
      
---
kind: Service
apiVersion: v1
metadata:
  name: website-crawler-service
  labels:
    app: website-crawler-service
    tier: backend
spec:
  selector:
    app: website-crawler-service
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http-ra-srv
  type: NodePort
